/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor */

#ifndef _Included_cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor
#define _Included_cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor
 * Method:    nativeAdd
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor_nativeAdd
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor
 * Method:    nativeDivide
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor_nativeDivide
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor
 * Method:    nativeMultiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor_nativeMultiply
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor
 * Method:    nativeExponentiate
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor_nativeExponentiate
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor
 * Method:    nativeSubtract
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_cr_ac_tec_appsmoviles_jnicalculator_calculator_processing_NativeArithmeticProcessor_nativeSubtract
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
